[2024-11-28 12:59:58] [ERROR] Error en toggle-pause - Context: {"action":"undefined","error":"Acción no especificada"}
[2024-11-28 13:01:07] [ERROR] Timeout en inicialización - Context: 
[2024-11-28 13:01:07] [ERROR] Error en start_detection - Context: {"message":"Timeout en la inicialización","trace":"#0 {main}"}
[2024-11-28 13:27:50] [ERROR] Error en descarga de Excel - Context: {"error":"El archivo Excel no existe","trace":"#0 {main}"}
[2024-11-28 13:45:01] [ERROR] Error en descarga de Excel - Context: {"error":"El archivo Excel no existe","trace":"#0 {main}"}
[2024-11-28 14:40:14] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:42:51] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:42:57] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:42:58] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:43:01] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:43:01] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:43:02] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:43:02] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:43:02] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:43:02] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:43:02] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:58:32] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 14:58:35] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:03:59] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:03:59] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:03:59] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:03] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:03] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:03] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:04] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:04] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:04] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:04] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:05] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:05] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:05] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:05] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:06] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:06] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:06] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:06] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:07] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:07] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:04:07] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:13] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:15] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:16] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:16] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:16] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:16] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:17] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:17] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:17] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:17] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:18] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:24:18] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:27:12] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-28 15:27:12] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-29 13:30:48] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-29 13:39:31] [ERROR] Error encontrado en log de Python - Context: 
[2024-11-29 13:39:31] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 13:46:05] [ERROR] Error en descarga de Excel - Context: {"error":"No hay detección activa","trace":"#0 {main}"}
[2024-11-29 17:18:35] [ERROR] Error encontrado en log de Python - Context: {"log":"Error conectando a base de datos: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 366, in <module>\r\n    system = DetectionSystem()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 36, in __init__\r\n    self.production_tracker = ProductionTracker()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 110, in __init__\r\n    self.db_connection = self._init_db_connection()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 116, in _init_db_connection\r\n    conn = psycopg2.connect(\r\n  File \"C:\\Users\\salos\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\r\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\r\npsycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\n"}
[2024-11-29 17:18:35] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 17:18:48] [ERROR] Error encontrado en log de Python - Context: {"log":"Error conectando a base de datos: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 366, in <module>\r\n    system = DetectionSystem()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 36, in __init__\r\n    self.production_tracker = ProductionTracker()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 110, in __init__\r\n    self.db_connection = self._init_db_connection()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 116, in _init_db_connection\r\n    conn = psycopg2.connect(\r\n  File \"C:\\Users\\salos\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\r\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\r\npsycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\n"}
[2024-11-29 17:18:48] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 17:21:15] [ERROR] Error encontrado en log de Python - Context: {"log":"Error conectando a base de datos: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 366, in <module>\r\n    system = DetectionSystem()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 36, in __init__\r\n    self.production_tracker = ProductionTracker()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 110, in __init__\r\n    self.db_connection = self._init_db_connection()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 116, in _init_db_connection\r\n    conn = psycopg2.connect(\r\n  File \"C:\\Users\\salos\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\r\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\r\npsycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\n"}
[2024-11-29 17:21:15] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 17:40:16] [ERROR] Error encontrado en log de Python - Context: {"log":"Error conectando a base de datos: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 366, in <module>\r\n    system = DetectionSystem()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 36, in __init__\r\n    self.production_tracker = ProductionTracker()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 110, in __init__\r\n    self.db_connection = self._init_db_connection()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 116, in _init_db_connection\r\n    conn = psycopg2.connect(\r\n  File \"C:\\Users\\salos\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\r\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\r\npsycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\n"}
[2024-11-29 17:40:16] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 17:53:33] [ERROR] Error encontrado en log de Python - Context: {"log":"Error conectando a base de datos: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 366, in <module>\r\n    system = DetectionSystem()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\main.py\", line 36, in __init__\r\n    self.production_tracker = ProductionTracker()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 110, in __init__\r\n    self.db_connection = self._init_db_connection()\r\n  File \"C:\\xampp\\htdocs\\L_Siembra\\backend\\python\\core\\data_management.py\", line 116, in _init_db_connection\r\n    conn = psycopg2.connect(\r\n  File \"C:\\Users\\salos\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\r\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\r\npsycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\r\n\r\n"}
[2024-11-29 17:53:33] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 17:55:17] [ERROR] Error encontrado en log de Python - Context: 
[2024-11-29 17:55:17] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 18:04:56] [ERROR] Error encontrado en log de Python - Context: 
[2024-11-29 18:04:56] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 18:06:21] [ERROR] Error encontrado en log de Python - Context: 
[2024-11-29 18:06:21] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-29 18:11:09] [ERROR] Error encontrado en log de Python - Context: 
[2024-11-29 18:11:09] [ERROR] Error en start_detection - Context: {"message":"Error en la inicialización de Python","trace":"#0 {main}"}
[2024-11-30 14:03:44] [ERROR] Error deteniendo detección - Context: {"error":"No hay detección en curso","trace":"#0 {main}"}
